export const DEFAULT_PACKAGES = [
  {
    name: "Starter",
    originalPrice: 25,
    discountedPrice: 12.5,
    tagline: "FEATURES OF STARTER PLAN",
    badge: "50% OFF",
    features: [
      "Job Post Expiry - 180 Days",
      "Credit Never Expire",
      "1 Job Posting",
    ],
    highlight: false,
    darkVariant: false,
    order: 1,
    credits: 1,
    expiryDays: 180,
    unlimitedJobs: false,
    active: true,
  },
  {
    name: "Deluxe",
    originalPrice: 95,
    discountedPrice: 47.5,
    tagline: "FEATURES OF DELUXE PLAN",
    badge: "Most Popular • 50% OFF",
    features: [
      "Job Post Expiry - 180 Days",
      "Credit Never Expire",
      "5 Job Posting",
    ],
    highlight: true,
    darkVariant: false,
    order: 2,
    credits: 5,
    expiryDays: 180,
    unlimitedJobs: false,
    active: true,
  },
  {
    name: "Ultimate",
    originalPrice: 195,
    discountedPrice: 97.5,
    tagline: "FEATURES OF ULTIMATE PLAN",
    badge: "50% OFF",
    features: [
      "Job Post Expiry - 180 Days",
      "Credit Never Expire",
      "10 Job Posting",
    ],
    highlight: false,
    darkVariant: false,
    order: 3,
    credits: 10,
    expiryDays: 180,
    unlimitedJobs: false,
    active: true,
  },
  {
    name: "Pro Plan",
    originalPrice: 380,
    discountedPrice: 190,
    tagline: "FEATURES OF PRO PLAN",
    badge: "Best Value • 50% OFF",
    features: [
      "Job Post Expiry - 180 Days",
      "Credit Never Expire",
      "20 Job Posting",
    ],
    highlight: false,
    darkVariant: false,
    order: 4,
    credits: 20,
    expiryDays: 180,
    unlimitedJobs: false,
    active: true,
  },
  {
    name: "Unlimited",
    originalPrice: 1350,
    discountedPrice: 675,
    tagline: "FEATURES OF UNLIMITED PLAN",
    badge: "Mega Deal • 50% OFF",
    features: [
      "Job Post Expiry - 180 Days",
      "Credit Expire 1 Year",
      "Unlimited Jobs Posting",
    ],
    highlight: false,
    darkVariant: true,
    order: 5,
    credits: 0,
    expiryDays: 365,
    unlimitedJobs: true,
    active: true,
  },
];
